-- Migration: RBAC permissions (4 actions per resource)
-- Run this on existing databases to add new permissions and link role Administrateur (2).
-- Safe to run multiple times (INSERT IGNORE).

INSERT IGNORE INTO `permission` (`module`, `code`, `name`) VALUES
('Tableau de bord', 'admin.dashboard', 'Tableau de bord – Accès'),
('Organisations', 'admin.organisations.view', 'Organisations – Voir'),
('Organisations', 'admin.organisations.add', 'Organisations – Ajout'),
('Organisations', 'admin.organisations.modify', 'Organisations – Modifier'),
('Organisations', 'admin.organisations.delete', 'Organisations – Supprimer'),
('Unités & Services', 'admin.units.view', 'Unités & Services – Voir'),
('Unités & Services', 'admin.units.add', 'Unités & Services – Ajout'),
('Unités & Services', 'admin.units.modify', 'Unités & Services – Modifier'),
('Unités & Services', 'admin.units.delete', 'Unités & Services – Supprimer'),
('Utilisateurs', 'admin.users.view', 'Utilisateurs – Voir'),
('Utilisateurs', 'admin.users.add', 'Utilisateurs – Ajout'),
('Utilisateurs', 'admin.users.modify', 'Utilisateurs – Modifier'),
('Utilisateurs', 'admin.users.delete', 'Utilisateurs – Supprimer'),
('Personnel', 'admin.staff.view', 'Personnel – Voir'),
('Personnel', 'admin.staff.add', 'Personnel – Ajout'),
('Personnel', 'admin.staff.modify', 'Personnel – Modifier'),
('Personnel', 'admin.staff.delete', 'Personnel – Supprimer'),
('Rôles & Accès', 'admin.roles.view', 'Rôles & Accès – Voir'),
('Rôles & Accès', 'admin.roles.add', 'Rôles & Accès – Ajout'),
('Rôles & Accès', 'admin.roles.modify', 'Rôles & Accès – Modifier'),
('Rôles & Accès', 'admin.roles.delete', 'Rôles & Accès – Supprimer'),
('Sécurité', 'admin.security.view', 'Sécurité – Voir'),
('Sécurité', 'admin.security.modify', 'Sécurité – Modifier'),
('Projets', 'admin.projects.view', 'Projets – Voir'),
('Projets', 'admin.projects.add', 'Projets – Ajout'),
('Projets', 'admin.projects.modify', 'Projets – Modifier'),
('Projets', 'admin.projects.delete', 'Projets – Supprimer'),
('Programmes', 'admin.programmes.view', 'Programmes – Voir'),
('Programmes', 'admin.programmes.add', 'Programmes – Ajout'),
('Programmes', 'admin.programmes.modify', 'Programmes – Modifier'),
('Programmes', 'admin.programmes.delete', 'Programmes – Supprimer'),
('Portfolios', 'admin.portfolios.view', 'Portfolios – Voir'),
('Portfolios', 'admin.portfolios.add', 'Portfolios – Ajout'),
('Portfolios', 'admin.portfolios.modify', 'Portfolios – Modifier'),
('Portfolios', 'admin.portfolios.delete', 'Portfolios – Supprimer'),
('Bailleurs', 'admin.bailleurs.view', 'Bailleurs – Voir'),
('Bailleurs', 'admin.bailleurs.add', 'Bailleurs – Ajout'),
('Bailleurs', 'admin.bailleurs.modify', 'Bailleurs – Modifier'),
('Bailleurs', 'admin.bailleurs.delete', 'Bailleurs – Supprimer'),
('Missions', 'admin.missions.view', 'Missions – Voir'),
('Missions', 'admin.missions.add', 'Missions – Ajout'),
('Missions', 'admin.missions.modify', 'Missions – Modifier'),
('Missions', 'admin.missions.delete', 'Missions – Supprimer'),
('Types de mission', 'admin.mission_types.view', 'Types de mission – Voir'),
('Types de mission', 'admin.mission_types.add', 'Types de mission – Ajout'),
('Types de mission', 'admin.mission_types.modify', 'Types de mission – Modifier'),
('Types de mission', 'admin.mission_types.delete', 'Types de mission – Supprimer'),
('Ordres de mission', 'admin.mission_orders.view', 'Ordres de mission – Voir'),
('Ordres de mission', 'admin.mission_orders.add', 'Ordres de mission – Ajout'),
('Ordres de mission', 'admin.mission_orders.modify', 'Ordres de mission – Modifier'),
('Ordres de mission', 'admin.mission_orders.delete', 'Ordres de mission – Supprimer'),
('Plans de mission', 'admin.mission_plans.view', 'Plans de mission – Voir'),
('Plans de mission', 'admin.mission_plans.add', 'Plans de mission – Ajout'),
('Plans de mission', 'admin.mission_plans.modify', 'Plans de mission – Modifier'),
('Plans de mission', 'admin.mission_plans.delete', 'Plans de mission – Supprimer'),
('Rapports de mission', 'admin.mission_reports.view', 'Rapports de mission – Voir'),
('Rapports de mission', 'admin.mission_reports.add', 'Rapports de mission – Ajout'),
('Rapports de mission', 'admin.mission_reports.modify', 'Rapports de mission – Modifier'),
('Rapports de mission', 'admin.mission_reports.delete', 'Rapports de mission – Supprimer'),
('Dépenses de mission', 'admin.mission_expenses.view', 'Dépenses de mission – Voir'),
('Dépenses de mission', 'admin.mission_expenses.add', 'Dépenses de mission – Ajout'),
('Dépenses de mission', 'admin.mission_expenses.modify', 'Dépenses de mission – Modifier'),
('Dépenses de mission', 'admin.mission_expenses.delete', 'Dépenses de mission – Supprimer'),
('Annonces', 'admin.announcements.view', 'Annonces – Voir'),
('Annonces', 'admin.announcements.add', 'Annonces – Ajout'),
('Annonces', 'admin.announcements.modify', 'Annonces – Modifier'),
('Annonces', 'admin.announcements.delete', 'Annonces – Supprimer'),
('Canaux', 'admin.channels.view', 'Canaux – Voir'),
('Canaux', 'admin.channels.add', 'Canaux – Ajout'),
('Canaux', 'admin.channels.modify', 'Canaux – Modifier'),
('Canaux', 'admin.channels.delete', 'Canaux – Supprimer'),
('Types de canaux', 'admin.channel_types.view', 'Types de canaux – Voir'),
('Types de canaux', 'admin.channel_types.add', 'Types de canaux – Ajout'),
('Types de canaux', 'admin.channel_types.modify', 'Types de canaux – Modifier'),
('Types de canaux', 'admin.channel_types.delete', 'Types de canaux – Supprimer'),
('Conversations', 'admin.conversations.view', 'Conversations – Voir'),
('Conversations', 'admin.conversations.add', 'Conversations – Ajout'),
('Conversations', 'admin.conversations.modify', 'Conversations – Modifier'),
('Conversations', 'admin.conversations.delete', 'Conversations – Supprimer'),
('Notifications', 'admin.notifications.view', 'Notifications – Voir'),
('Notifications', 'admin.notifications.add', 'Notifications – Ajout'),
('Notifications', 'admin.notifications.modify', 'Notifications – Modifier'),
('Notifications', 'admin.notifications.delete', 'Notifications – Supprimer'),
('Commentaires', 'admin.comments.view', 'Commentaires – Voir'),
('Commentaires', 'admin.comments.add', 'Commentaires – Ajout'),
('Commentaires', 'admin.comments.modify', 'Commentaires – Modifier'),
('Commentaires', 'admin.comments.delete', 'Commentaires – Supprimer'),
('Pièces jointes', 'admin.attachments.view', 'Pièces jointes – Voir'),
('Pièces jointes', 'admin.attachments.add', 'Pièces jointes – Ajout'),
('Pièces jointes', 'admin.attachments.modify', 'Pièces jointes – Modifier'),
('Pièces jointes', 'admin.attachments.delete', 'Pièces jointes – Supprimer'),
('Historique communication', 'admin.communication_history.view', 'Historique communication – Voir'),
('Historique communication', 'admin.communication_history.add', 'Historique communication – Ajout'),
('Historique communication', 'admin.communication_history.modify', 'Historique communication – Modifier'),
('Historique communication', 'admin.communication_history.delete', 'Historique communication – Supprimer'),
('Documents', 'admin.documents.view', 'Documents – Voir'),
('Documents', 'admin.documents.add', 'Documents – Ajout'),
('Documents', 'admin.documents.modify', 'Documents – Modifier'),
('Documents', 'admin.documents.delete', 'Documents – Supprimer'),
('Planning & KPI', 'admin.planning.view', 'Planning & KPI – Voir'),
('Planning & KPI', 'admin.planning.modify', 'Planning & KPI – Modifier');

INSERT IGNORE INTO `role_permission` (`role_id`, `permission_id`)
SELECT 2, id FROM `permission`;
